version: '3.8'
services:
  web:
    depends_on:
      - postgres_db
      - api
    ports:
      - 8006:8000
    env_file:
      - web/.env
    build: 
      context: ./web/
      dockerfile: Dockerfile
    volumes:
      - ./web/:/app/

  api:
    depends_on:
      - postgres_db
    ports:
      - 8001:8001
    build:
      context: ./api/
      dockerfile: Dockerfile
  postgres_db:
    image: postgres 
    restart: always
    env_file:
      - web/.env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
