# Generated by Django 4.2.10 on 2024-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_cryptoapi"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sepal_length", models.FloatField()),
                ("sepal_width", models.FloatField()),
                ("petal_length", models.FloatField()),
                ("petal_width", models.FloatField()),
            ],
        ),
    ]
