# Generated by Django 4.2.10 on 2024-03-05 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functionalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ModelApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('Bank', models.CharField(max_length=100)),
                ('BankState', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('NAICS', models.CharField(choices=[('11', 'Agriculture, forestry, fishing and hunting'), ('21', 'Mining, quarrying, and oil and gas extraction'), ('22', 'Utilities'), ('23', 'Construction'), ('31-33', 'Manufacturing'), ('42', 'Wholesale trade'), ('44-45', 'Retail trade'), ('48-49', 'Transportation and warehousing'), ('51', 'Information'), ('52', 'Finance and insurance'), ('53', 'Real estate and rental and leasing'), ('54', 'Professional, scientific, and technical services'), ('55', 'Management of companies and enterprises'), ('56', 'Administrative and support and waste management and remediation services'), ('61', 'Educational services'), ('62', 'Health care and social assistance'), ('71', 'Arts, entertainment, and recreation'), ('72', 'Accommodation and food services'), ('81', 'Other services (except public administration) 92 Public administration')], max_length=10)),
                ('Term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('NoEmp', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('NewExist', models.BooleanField(choices=[(True, 'New'), (False, 'Existing')])),
                ('CreateJob', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('RetainedJob', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('UrbanRural', models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural'), ('unknown', 'Undefined')], max_length=10)),
                ('RevLineCr', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('LowDoc', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')])),
                ('GrAppv', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('SBA_Appv', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('Franchise', models.BooleanField(choices=[(0, 'No'), (1, 'Yes')])),
            ],
        ),
    ]
