# Generated by Django 4.2.10 on 2024-03-05 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelapi',
            name='ApprovalDate',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Date must be in the format YYYY-MM-DD', regex='^\\d{4}-\\d{2}-\\d{2}$')]),
        ),
    ]
